[project]
name = "mcp-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.11.18",
    "fastmcp>=2.3.4",
    "pydantic>=2.11.4",
    "uvicorn>=0.34.2",
    "fastmcp>=2.4.0",
    "httpx>=0.28.1",
]
